# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEPLOY_ENV: prod
  GITHUB_ACTIONS: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # ===========================================================================
  # Prepare Images
  # ===========================================================================
  pre-commit:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      # Checkout "master"
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Prepare Dataset from Excel file for Site
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Latest stable
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/python/requirements.txt
      - name: Convert Excel to JSON
        run: |
          python ./src/python/excel_to_json.py --conf ./src/python/config.$DEPLOY_ENV.yml

      # Prepare Optimized Tiles
#      - name: Convert SVG to PNG using rsvg-convert
#        run: |
#          sudo apt-get -y install librsvg2-bin
#          cd ./images/tiles
#          for i in *.svg;
#          do
#            png_file=${i%.*}.png;
#            if [ ! -f ${png_file} ]; then
#              echo "Converting ${i} to ${png_file}"
#              rsvg-convert --format="png" --width=720 "$i" > "${png_file}";
#            fi
#          done;
#          tree -s "$GITHUB_WORKSPACE"

      # See here for further info : https://schnerring.net/blog/checking-out-code-committed-within-the-same-github-actions-workflow-run/
      - name: Update CHANGELOG.md
        run: echo "Added automatic changes on $(date)" >> CHANGELOG.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: commit-and-push
        with:
          commit_message: Automatic data refresh
          status_options: '--untracked-files=yes'


  # ===========================================================================
  # Build job
  # ===========================================================================
  build:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      # Checkout "master"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.pre-commit.outputs.commit_hash }}

      # Move elements to Assets
      - name: Move images to site assets
        run: |
          echo "Move event dataset to Assets"
          cp ./data/events.json ./docs/_data/events.json
          echo "Move PNG tiles to Assets"
          mkdir -p ./docs/assets/images/tiles
          cp ./images/tiles/*.png ./docs/assets/images/tiles
          tree -a ./docs/assets

      # Prepare Jekyll Site
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: _site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
