# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Repository Dispatch Trigger - Google Drive Push

on:
  # Runs on pushes targeting the default branch
  repository_dispatch:
    types: [create-pull-request-from-gs]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEPLOY_ENV: prod
  GITHUB_ACTIONS: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  # ===========================================================================
  # Create Pull Request
  # ===========================================================================
  pull-request:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
      pull-requests: write

    steps:
      # Checkout "master"
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GS_SERVICE_ACCOUNT }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > "$GITHUB_WORKSPACE/src/python/service_account_key.json"
          tree -s "$GITHUB_WORKSPACE"

      # Prepare Dataset from Excel file for Site
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Latest stable
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/python/requirements.txt
      - name: Pull Google Drive Content
        run: |
          python ./src/python/gdrive_agenda_helper.py --conf ./src/python/config.$DEPLOY_ENV.yml

      # See here for further info : https://schnerring.net/blog/checking-out-code-committed-within-the-same-github-actions-workflow-run/
      - name: Update CHANGELOG.md
        run: echo "Updated repo from Google Drive on $(date)" >> CHANGELOG.md

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_WORKFLOW_PAT_TOKEN }}
          commit-message: Refresh data with Google Drive
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: online-updates
          delete-branch: true
          title: '[Automatic] Data and image refresh'
          body: |
            Refresh data with Google Drive
            - Updated with *today's* data
          labels: |
            automated pr
          assignees: zyniel
          reviewers: zyniel
          draft: false
