# config.prod.yml
excel_file: ./WCS.xlsx
excel_worksheet: "Dernier"
json_file: ./data/events.json

app:
  data_file: ./data/events.json
  png_folder: ./images/tiles
  svg_folder: ./images/tiles-svg
  export_folder: ./exports
drive:
  service_account_key: ./src/python/service_account_key.json
  png_folder_id: '1bmGBmOOWCJbDe7A3-b_WY_MzndMsCb2i'
  svg_folder_id: '1NjholefBcuA-yiGAb3IT_KIp2zHKC5qU'
sheets:
  service_account_key: ./src/python/service_account_key.json
  spreadsheet_id: '1UqPalww9jVR9FDn6WDNxSZbiL9sRsomTKQWBer1CMA8'
  data:
    worksheet_id: 'Semaine'
    data_range: 'TblSemaine'
    date_column: 'Date Début'
  config:
    worksheet_id: 'Config'
    pre_survey_cell: 'RNG_PRESURVEY'
    post_survey_cell: 'RNG_POSTSURVEY'
    pre_links_cell: 'RNG_PRELINKS'
    post_links_cell: 'RNG_POSTLINKS'