# =============================================================================
# DEVELOPPEMENT CONFIGURATION FILE
# =============================================================================
app:
  data_file: ./data/events.json
  misc_folder: ./images/misc
  png_folder: ./images/tiles
  svg_folder: ./images/tiles-svg
  export_folder: ./exports
community:
  name: 'Test Westies (2024)'
  survey_recipients:
    - 'Test Coast Swing (2024/2025)'
    - "François CABANNES"
  planning_recipients:
    - 'Test Coast Swing (2024/2025)'
  send_survey : true
  send_planning : true
mail:
  to: 'cabannes.francois.dance@gmail.com'
  sender: 'cabannes.francois.dance@gmail.com'
  subject: '[TW] Enter QR Code to login'
drive:
  service_account_key: ./src/python/google_service_account_key.json
  png_folder_id: '1bmGBmOOWCJbDe7A3-b_WY_MzndMsCb2i'
  svg_folder_id: '1NjholefBcuA-yiGAb3IT_KIp2zHKC5qU'
sheets:
  service_account_key: ./src/python/google_service_account_key.json
  spreadsheet_id: '14li6xxH3nWr3S9GvBvR_vXDdYl0zdwOUFnOnrw0sees'
  named_ranges:
    week_range: 'TblSemaine'
    config_range: 'TblConfig'
  data:
    worksheet_id: 'Semaine'
    columns:
      start_time: 'Date Début'
      end_date: 'Heure Début'
      end_time: 'Date Fin'
      start_day: 'Heure Fin'
      type: 'Type'
      owner: 'Organisateur'
      place: 'Salle'
      location: 'Lieu'
      city: 'Ville'
      address: 'Adresse'
      event_name: 'Nom'
      event_shortname: 'Nom Court'
      short_url: 'Lien Court'
      url: 'Lien'
      image: 'Image'
      survey_text: 'Sondage'
      planning_text: 'Planning'
      infos_text: 'Infos'
      order: 'Ordre'
  config:
    worksheet_id: 'Config'
    columns:
      parameter: 'Parametre'
      value: 'Valeur'
  whatsapp:
    worksheet_id: 'WhatsApp'
    columns:
      infos: 'Liens'
      survey: 'Choix'
chrome:
  user_dir_folder: 'I:\git\westie-agenda\chrome\'
  virtual_display: false
imagekit:
  public_key: 'public_qPe0Bz3r3v+RJi5u7+byZp/TcKQ='
  url_endpoint: 'https://ik.imagekit.io/templewesties'
  png_folder: '/westie-agenda/tiles'
  svg_folder: '/westie-agenda/tiles-svg'
mosaic:
  grid_layouts:
    1: [ 1, 1 ]
    2: [ 2, 1 ]
    3: [ 2, 2 ]
    4: [ 2, 2 ]
    5: [ 2, 3 ]
    6: [ 2, 3 ]
    7: [ 2, 4 ]
    8: [ 3, 3 ]
    9: [ 3, 3 ]
    10: [ 2, 5 ]
    11: [ 4, 3 ]
    12: [ 4, 3 ]
  background_color: '#171717'
  main_font_color: '#dcd7c9ff'
  header_height: 130
  footer_height: 0
  padding:
    top: 55
    left: 55
    right: 55
    bottom: 55
  logo:
    file: 'logo-fcbs-150px.png'
    size:
      width: 31
      height: 150
  title:
    font_color: '#dcd7c9ff'
    font_file: 'luckiestguy.ttf'
    font_size: 95
    padding:
      top: 55
      left: 55
      right: 55
      bottom: 55
  event:
    title:
      font_color: '#dcd7c9ff'
      font_file: 'NotoSans-Bold.ttf'
      font_size: 40
      padding:
        top: 0
        left: 0
        right: 0
        bottom: 15
    banner:
      size:
        width: 720
        height: 419
      padding:
        top: 0
        left: 0
        right: 0
        bottom: 0
      border:
        top: 0
        left: 0
        right: 0
        bottom: 0
    spacing:
      right: 36
      bottom: 36

