name: Push to WhatsApp - Common

on:
  workflow_call:
    inputs:
      deploy_env:
        required: true
        type: string
    secrets:
      GM_SERVICE_ACCOUNT:
        required: true
      CHROME_PROFILE_PWD:
        required: true

jobs:

  # ===========================================================================
  # Scenario to automate WhatsApp using Selenium to publish Temple Westies
  # weekly Surveys and Plannings
  # ===========================================================================
  commit:
    runs-on: ubuntu-latest

    # Set proper permissions for GITHUB_TOKEN to create, push and write content.
    # Needed to create content and checkout
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Identify - ${{github.event.client_payload.id}}
        run: echo Run identifier ${{ github.event.client_payload.id }}

      # Checkout "master"
      - name: Checkout
        uses: actions/checkout@v4

      # Setup python environment - reuse cache if possible
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/requirements.*.txt'

      # Build python environment
      - name: Install dependencies
        run: |
          pip install -r ./src/python/requirements.notifier.txt
          sudo apt-get update -y
          sudo apt install x11-utils gnumeric xvfb xclip p7zip-full

      # Install chrome
      - uses: browser-actions/setup-chrome@v1
        id: browser-setup
        with:
          chrome-version: ${{ vars.CHROME_VERSION }}
          install-dependencies: true
          install-chromedriver: true

      # Unzip private chrome profile.
      # NOTE: Secured by password
      # TODO: Find a better solution with cache ??
      - name: Unpack Chrome Profile
        env:
          CHROME_PROFILE_PWD: ${{ secrets.CHROME_PROFILE_PWD }}
        run: |
          unzip -P "$CHROME_PROFILE_PWD" ./chrome/__profile/chrome-profile.zip -d ./chrome/

      # Main processing
      - name: Pull Google Drive Content
        env:
          GM_SERVICE_ACCOUNT: ${{ secrets.GM_SERVICE_ACCOUNT }}
          VIRTUAL_DISPLAY: '1'
        run: |
          python ./src/python/community_notifier.py \
            --conf ./src/python/config.${{ inputs.deploy_env }}.yml \
            --browser-version "${{ steps.browser-setup.outputs.chrome-version }}"
            --browser-bin-path "${{ steps.browser-setup.outputs.chrome-path }}"
            --driver-bin-path " ${{ steps.browser-setup.outputs.chromedriver-path }}"
