name: Sync GDrive and deploy GitHub Pages (Test)

on:
  workflow_dispatch: {}

jobs:
  call-common:
    uses: ./.github/workflows/github-actions-update-from-gdrive-common.yml
    with:
      deploy_env: test
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GS_SERVICE_ACCOUNT: ${{ secrets.GS_SERVICE_ACCOUNT }}
      IK_SERVICE_ACCOUNT: ${{ secrets.IK_SERVICE_ACCOUNT }}
