name: Pre-Commit Excel to JSON Conversion
on: [push, pull_request]

jobs:
  convert-xlsx-to-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/python/requirements.txt

      - name: Convert Excel to JSON
        run: |
          python ./src/python/excel_to_json.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./data/WCS.json
          git commit -m 'Convert Excel to JSON'
          git push