name: Sync GDrive and deploy GitHub Pages - Common

on:
  workflow_call:
    inputs:
      deploy_env:
        required: true
        type: string
    secrets:
      GS_SERVICE_ACCOUNT:
        required: true
      IK_SERVICE_ACCOUNT:
        required: true

jobs:
  commit:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - name: Identify - ${{github.event.client_payload.id}}
        run: echo Run identifier ${{ github.event.client_payload.id }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GS_SERVICE_ACCOUNT }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > "$GITHUB_WORKSPACE/src/python/google_service_account_key.json"
          tree -s "$GITHUB_WORKSPACE"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/requirements.builder.txt'

      - name: Install dependencies
        run: |
          pip install -r ./src/python/requirements.builder.txt

      - name: Pull Google Drive Content
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GS_SERVICE_ACCOUNT }}
          IK_SERVICE_ACCOUNT: ${{ secrets.IK_SERVICE_ACCOUNT }}
        run: |
          python ./src/python/community_site_builder.py --conf ./src/python/config.${{ inputs.deploy_env }}.yml
          tree -s "$GITHUB_WORKSPACE"

      - name: Update CHANGELOG.md
        run: |
          printf -- "\r\n" >> CHANGELOG.md
          printf -- "## $(date '+%Y%m%d-%H%M%S')\r\n" >> CHANGELOG.md
          printf -- "\r\n" >> CHANGELOG.md
          printf -- "### Added\r\n" >> CHANGELOG.md
          printf -- "\r\n" >> CHANGELOG.md
          printf -- "- Updated pictures from Google Drive\r\n" >> CHANGELOG.md
          printf -- "- Updated events.json from Google Drive\r\n" >> CHANGELOG.md
          printf -- "- Created export image\r\n" >> CHANGELOG.md
          printf -- "" >> CHANGELOG.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: commit-and-push
        with:
          commit_message: Automatic data refresh
          status_options: '--untracked-files=yes'
          push_options: '--force'
          add_options: '-u'

  build:
    runs-on: ubuntu-latest
    needs: commit
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.commit.outputs.commit_hash }}

      - name: Move images to site assets
        run: |
          echo "Move event dataset to Assets"
          cp ./data/events.json ./docs/_data/events.json
          tree -a ./docs/assets

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
