name: Push to WhatsApp (Test)

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [Push to WhatsApp (Test)]

jobs:
  call-common:
    uses: ./.github/workflows/github-actions-push-to-wa-common.yml
    with:
      deploy_env: test
    secrets:
      GM_SERVICE_ACCOUNT: ${{ secrets.GM_SERVICE_ACCOUNT }}
      CHROME_PROFILE_PWD: ${{ secrets.CHROME_PROFILE_PWD }}
