# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Refresh from GDrive and Build GH Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}
  # Allows you to run this workflow programmatically
  repository_dispatch:
    types: [gsa_sheets_trigger]

env:
  DEPLOY_ENV: prod
  GITHUB_ACTIONS: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # ===========================================================================
  # Download, update and Commit
  # ===========================================================================
  pre-commit:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
      pull-requests: write

    steps:
      # Checkout "master"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GS_SERVICE_ACCOUNT }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > "$GITHUB_WORKSPACE/src/python/service_account_key.json"
          tree -s "$GITHUB_WORKSPACE"

      # Prepare Dataset from Excel file for Site
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Latest stable
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/python/requirements.txt
      - name: Pull Google Drive Content
        run: |
          python ./src/python/gdrive_agenda_helper.py --conf ./src/python/config.$DEPLOY_ENV.yml

      # See here for further info : https://schnerring.net/blog/checking-out-code-committed-within-the-same-github-actions-workflow-run/
      - name: Update CHANGELOG.md
        run: printf "Updated repo from Google Drive on $(date)\n" >> CHANGELOG.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: commit-and-push
        with:
          commit_message: Automatic data refresh
          status_options: '--untracked-files=yes'
