name: Sync GDrive and deploy GitHub Pages - Common

on:
  workflow_call:
    inputs:
      deploy_env:
        required: true
        type: string
    secrets:
      GS_SERVICE_ACCOUNT:
        required: true
      IK_SERVICE_ACCOUNT:
        required: true

jobs:

  # ===========================================================================
  # Pull Google Drive content, build and prepare material to build the GitHub
  # Pages and WhatsApp broadcasts.
  # ===========================================================================
  commit:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    # Set proper permissions for GITHUB_TOKEN to create, push and write content.
    # Needed to create content and new files, manage PR using plugin and build/deploy on GHP
    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - name: Identify - ${{github.event.client_payload.id}}
        run: echo Run identifier ${{ github.event.client_payload.id }}

      # Checkout "master" with proper depth
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: '0'

      # Spool Google Cloud Platform API Key to file for python Service Account Auth
      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GS_SERVICE_ACCOUNT }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > "$GITHUB_WORKSPACE/src/python/google_service_account_key.json"

      # Setup python environment - reuse cache if possible
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/requirements.builder.txt'

      # Build python environment
      - name: Install dependencies
        run: |
          pip install -r ./src/python/requirements.builder.txt

      # Main processing
      - name: Pull Google Drive Content
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GS_SERVICE_ACCOUNT }}
          IK_SERVICE_ACCOUNT: ${{ secrets.IK_SERVICE_ACCOUNT }}
        run: |
          python ./src/python/community_site_builder.py --conf ./src/python/config.${{ inputs.deploy_env }}.yml

      # Track changes inside the dynamic CHANGELOG.md
      - name: Add created files and Update CHANGELOG.md
        run: |
          ./src/shell/update_changelog.sh

      # Commit all changes
      # TODO : Should be a new PR instead
      - uses: stefanzweifel/git-auto-commit-action@v5
        id: commit-and-push
        with:
          commit_message: Automatic data refresh
          status_options: '--untracked-files=yes'
          push_options: '--force'
          add_options: '-u'

  # ===========================================================================
  # Build the GitHub Pages bundle with mandatory event data files
  # ===========================================================================
  build:
    runs-on: ubuntu-latest
    needs: commit
    steps:
      # Checkout "master"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.commit.outputs.commit_hash }}

      # Include the weekly data export
      - name: Move images to site assets
        run: |
          echo "Move event dataset to Assets"
          cp ./data/events.json ./docs/_data/events.json

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # ===========================================================================
  # Deploy the GitHub Pages bundle
  # ===========================================================================
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
